### ISSUE TITLE
Correct YAML Configuration

### ISSUE THREAD

**Issue by erockdotdev** [CircleCI-Public/circleci-demo-javascript-react-app#67]
Hi - not sure if this is the right place but the [config.yml](https://github.com/CircleCI-Public/circleci-demo-javascript-react-app/blob/master/.circleci/config.yml) on master really deviates from whats noted in the read me (involving slack and some scheduled job). 

Additionally, referencing the readme alone doesn't really seem to match what is noted as "[the] best practice for using version 2.1" as it looks like its just running the node test(?)

Going back in the [history](https://github.com/CircleCI-Public/circleci-demo-javascript-react-app/commits/master/.circleci/config.yml) there seems to be some pretty distinct versions of this file too. As someone new and looking for what the best practices are I cant really make sense of what that might be. 

Is there any available reference that does show what the best practice for a node app might be? or if it is here can we have a little more of an explanation of the parts that are not in any of the tutorials leading up to here? (- slack/notify, cron: "0 0 * * *"  , etc.)

**Comment by jkzilla** [comment]
Hi @erockdotdev thank you for noting this! that was a mistake on my part and we are working on an update. Thank you for your patience!

**Comment by erockdotdev** [comment]
Oh - Cool! no worries!!! thanks for taking a look at this!
